In [26]:
import os, sys

# Add project root (D:\crimewatch) to Python path
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("✅ Project root:", PROJECT_ROOT)

✅ Project root: d:\crimewatch

In [27]:
from src.data_loader import load_india_crime
print("✅ src import working!")

✅ src import working!

In [4]:
import os, sys

# ✅ Add project root (D:\crimewatch) to Python path
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("Project root added:", PROJECT_ROOT)

Project root added: d:\crimewatch

In [5]:
from src.data_loader import load_india_crime
print("✅ src import working!")

✅ src import working!

In [1]:
import pandas as pd

In [2]:
import sys
from pathlib import Path

# Add project root to path
BASE_DIR = Path().resolve().parent
sys.path.append(str(BASE_DIR))

In [3]:
from src.data_loader import load_india_crime

df = load_india_crime()
df.head()

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [2]:
import sys
print(sys.executable)

c:\Users\rajav\AppData\Local\Programs\Python\Python313\python.exe

In [1]:
import matplotlib
import seaborn
print("matplotlib:", matplotlib.__version__)
print("seaborn:", seaborn.__version__)

matplotlib: 3.10.7
seaborn: 0.13.2

In [6]:
import os
import sys

# Add project root to Python path so we can import src.*
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(".")))
if BASE_DIR not in sys.path:
    sys.path.append(BASE_DIR)

from src.data_loader import load_india_crime

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

In [7]:
# This will work after we add india_crime_ncrb.csv
# df_india = load_india_crime()
# df_india.head()

In [8]:
from src.data_loader import load_india_crime

df = load_india_crime()
df.shape, df.columns

((5322, 124),
 Index(['id', 'year', 'state_name', 'state_code', 'district_name',
        'district_code', 'registration_circles', 'murder',
        'clpbl_hmcrd_not_amt_murder', 'hit_and_run',
        ...
        'ofnc_religion', 'cheating_impersonation', 'ofnc_mischief', 'arson',
        'criminal_trespass', 'crlty_husbnd_relatives',
        'crcl_false_fake_news_rumours', 'criminal_intimidation',
        'insult_modesty_women', 'other_ipc_crimes'],
       dtype='object', length=124))

In [9]:
df.head()

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [10]:
# try common year column names
for col in ["year", "Year", "crime_year"]:
    if col in df.columns:
        print(col, sorted(df[col].dropna().unique())[:10], " ... ", sorted(df[col].dropna().unique())[-5:])

year [np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022)]  ...  [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022)]

In [11]:
from src.data_loader import load_india_crime

df = load_india_crime()

df.shape

(5322, 124)

In [12]:
df.columns

Index(['id', 'year', 'state_name', 'state_code', 'district_name',
       'district_code', 'registration_circles', 'murder',
       'clpbl_hmcrd_not_amt_murder', 'hit_and_run',
       ...
       'ofnc_religion', 'cheating_impersonation', 'ofnc_mischief', 'arson',
       'criminal_trespass', 'crlty_husbnd_relatives',
       'crcl_false_fake_news_rumours', 'criminal_intimidation',
       'insult_modesty_women', 'other_ipc_crimes'],
      dtype='object', length=124)

In [13]:
df.head(3)

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0

In [16]:
import pandas as pd

master = pd.read_csv("../data/processed/master_crime_long.csv")  # notebook is inside notebooks/
print(master.shape)
print(master.columns)
print(master["category"].value_counts())
print(master["year"].min(), master["year"].max())

(2870817, 10)
Index(['year', 'state_name', 'state_code', 'district_name', 'district_code',
       'registration_circles', 'crime_type', 'crime_count', 'category',
       'source_file'],
      dtype='object')
category
ipc_total                 627996
ipc_by_juveniles          627996
sll_crimes                388433
crime_against_children    276692
crime_against_women       228811
cyber_crime               223524
crime_against_st          213252
crime_against_sc          207597
missing_persons            76516
Name: count, dtype: int64
2017 2022

In [17]:
meta_cols = [
    "year",
    "state_name",
    "district_name",
    "state_code",
    "district_code"
]

crime_cols = [c for c in df.columns if c not in meta_cols]
len(crime_cols), crime_cols[:10]

(119,
 ['id',
  'registration_circles',
  'murder',
  'clpbl_hmcrd_not_amt_murder',
  'hit_and_run',
  'acdnt_other_than_hit_and_run_',
  'deaths_negl_rel_rail_acdnt',
  'deaths_due_med_negnc',
  'deaths_neg_civic_bodies',
  'deaths_other_negnc'])

In [18]:
df_long = df.melt(
    id_vars=meta_cols,
    value_vars=crime_cols,
    var_name="crime_type",
    value_name="crime_count"
)

df_long.head()

,year,state_name,district_name,state_code,district_code,crime_type,crime_count
0,2017,Andhra Pradesh,Ananthapuramu,28,502,id,0
1,2017,Andhra Pradesh,Chittoor,28,503,id,1
2,2017,Andhra Pradesh,Y.S.R.,28,504,id,2
3,2017,Andhra Pradesh,East Godavari,28,505,id,3
4,2017,Andhra Pradesh,Ananthapuramu,28,502,id,4

In [19]:
df_long.shape

(633318, 7)

In [20]:
df_long.isna().sum().sort_values(ascending=False).head(10)

crime_count      3615
state_name          0
year                0
district_name       0
state_code          0
district_code       0
crime_type          0
dtype: int64

In [21]:
df_long["crime_count"].describe()

count     629703
unique      6529
top            0
freq      398719
Name: crime_count, dtype: int64

In [22]:
df_long["crime_count"] = (
    pd.to_numeric(df_long["crime_count"], errors="coerce")
    .fillna(0)
)

In [23]:
df_long["crime_count"].dtype

dtype('float64')

In [25]:
import sys
print(sys.executable)

d:\crimewatch\venv\Scripts\python.exe

In [28]:
import pandas as pd

master = pd.read_csv("../data/processed/master_crime_long.csv")
master.head()

,year,state_name,state_code,district_name,district_code,registration_circles,crime_type,crime_count,category,source_file
0,2022,Andhra Pradesh,28,Alluri Sitharama Raju,745,Alluri Sitharama Raju,id,0.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
1,2022,Andhra Pradesh,28,Anakapalli,744,Anakapalli,id,1.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
2,2022,Andhra Pradesh,28,Anantapur,502,Anantapuramu,id,2.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
3,2022,Andhra Pradesh,28,Annamayya,753,Annamayya,id,3.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
4,2022,Andhra Pradesh,28,Bapatla,750,Bapatla,id,4.0,crime_against_children,districtwise-crime-against-children-2017-onwar...

In [30]:
print(master.shape)
print(master.columns)

print("Missing crime_count:", master["crime_count"].isna().sum())
print("crime_count dtype:", master["crime_count"].dtype)

print("\nCategory counts:")
print(master["category"].value_counts())

print("\nYear range:")
print(master["year"].min(), master["year"].max())

(2870817, 10)
Index(['year', 'state_name', 'state_code', 'district_name', 'district_code',
       'registration_circles', 'crime_type', 'crime_count', 'category',
       'source_file'],
      dtype='object')
Missing crime_count: 0
crime_count dtype: float64

Category counts:
category
ipc_total                 627996
ipc_by_juveniles          627996
sll_crimes                388433
crime_against_children    276692
crime_against_women       228811
cyber_crime               223524
crime_against_st          213252
crime_against_sc          207597
missing_persons            76516
Name: count, dtype: int64

Year range:
2017 2022

In [32]:
import pandas as pd

df = pd.read_csv("../data/raw/districtwise-ipc-crimes-2017-onwards.csv")
df.head()

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [33]:
import os
print(os.getcwd())

d:\crimewatch\notebooks

In [34]:
import pandas as pd

df = pd.read_csv(r"../data/raw/districtwise-ipc-crimes-2017-onwards.csv")
df.head()

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [35]:
import os
import pandas as pd

BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))
print("BASE_DIR =", BASE_DIR)

file_path = os.path.join(BASE_DIR, "data", "raw", "districtwise-ipc-crimes-2017-onwards.csv")

print("file exists?", os.path.exists(file_path))

df = pd.read_csv(file_path)
df.head()

BASE_DIR = d:\crimewatch
file exists? True

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [36]:
import pandas as pd

# columns that are not crimes
id_cols = [
    "id", "year", "state_name", "state_code",
    "district_name", "district_code", "registration_circles"
]

crime_cols = [c for c in df.columns if c not in id_cols]

df_long = df.melt(
    id_vars=["year", "state_name", "district_name"],
    value_vars=crime_cols,
    var_name="crime_type",
    value_name="crime_count"
)

# Ensure numeric
df_long["crime_count"] = pd.to_numeric(df_long["crime_count"], errors="coerce").fillna(0)

df_long.head()

   year      state_name  district_name crime_type  crime_count
0  2017  Andhra Pradesh  Ananthapuramu     murder        113.0
1  2017  Andhra Pradesh       Chittoor     murder         70.0
2  2017  Andhra Pradesh         Y.S.R.     murder         88.0
3  2017  Andhra Pradesh  East Godavari     murder         69.0
4  2017  Andhra Pradesh  Ananthapuramu     murder         11.0

In [37]:
district_totals = (
    df_long.groupby(["year", "state_name", "district_name"], as_index=False)
    .agg(total_crime=("crime_count", "sum"))
)

district_totals.sort_values("total_crime", ascending=False).head(10)

      year   state_name   district_name  total_crime
2676  2020   Tamil Nadu         Chennai      89611.0
3992  2022  Maharashtra          Mumbai      83073.0
2706  2020   Tamil Nadu  Tiruvannamalai      82696.0
1083  2018  Maharashtra          Mumbai      80052.0
1558  2019        Delhi      North West      76637.0
1793  2019  Maharashtra          Mumbai      74490.0
3756  2022        Delhi      North West      74011.0
3008  2021        Delhi      North West      72981.0
849   2018        Delhi      North West      71219.0
2287  2020      Gujarat       Ahmadabad      70800.0

In [38]:
state_totals = (
    df_long.groupby(["year", "state_name"], as_index=False)
    .agg(total_crime=("crime_count", "sum"))
)

state_totals.sort_values(["year", "total_crime"], ascending=[False, False]).head(15)

     year      state_name  total_crime
213  2022   Uttar Pradesh     401787.0
199  2022     Maharashtra     374038.0
187  2022           Delhi     300429.0
198  2022  Madhya Pradesh     298578.0
207  2022       Rajasthan     236090.0
195  2022          Kerala     226919.0
184  2022           Bihar     211079.0
209  2022      Tamil Nadu     193913.0
181  2022  Andhra Pradesh     158547.0
215  2022     West Bengal     156503.0
210  2022       Telangana     151849.0
204  2022          Odisha     143414.0
189  2022         Gujarat     134600.0
194  2022       Karnataka     129461.0
190  2022         Haryana     125435.0

In [39]:
import pandas as pd
import os

print("Current folder:", os.getcwd())

master_path = "../data/processed/master_crime_long.csv"
master = pd.read_csv(master_path, nrows=50000)   # fast test load
print("Loaded rows:", master.shape)
master.head()

Current folder: d:\crimewatch\notebooks
Loaded rows: (50000, 10)

,year,state_name,state_code,district_name,district_code,registration_circles,crime_type,crime_count,category,source_file
0,2022,Andhra Pradesh,28,Alluri Sitharama Raju,745,Alluri Sitharama Raju,id,0.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
1,2022,Andhra Pradesh,28,Anakapalli,744,Anakapalli,id,1.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
2,2022,Andhra Pradesh,28,Anantapur,502,Anantapuramu,id,2.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
3,2022,Andhra Pradesh,28,Annamayya,753,Annamayya,id,3.0,crime_against_children,districtwise-crime-against-children-2017-onwar...
4,2022,Andhra Pradesh,28,Bapatla,750,Bapatla,id,4.0,crime_against_children,districtwise-crime-against-children-2017-onwar...

In [40]:
import os
import pandas as pd

RAW_DIR = "../data/raw"
file_path = os.path.join(RAW_DIR, "districtwise-ipc-crimes-2017-onwards.csv")

df = pd.read_csv(file_path)
df.head()

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0

In [41]:
master = pd.read_csv("../data/processed/master_crime_long.csv")

# Create state-wise yearly totals (for dashboard charts)
state_year = (
    master.groupby(["year", "state_name"], as_index=False)
          .agg(total_crime=("crime_count", "sum"))
)

state_year.head()

   year                   state_name  total_crime
0  2017  Andaman And Nicobar Islands      71364.0
1  2017               Andhra Pradesh     392867.0
2  2017            Arunachal Pradesh     156084.0
3  2017                        Assam     440398.0
4  2017                        Bihar     615218.0

In [42]:
import pandas as pd

master = pd.read_csv("../data/processed/master_crime_long.csv")

# 1) State-wise yearly totals
state_year = (
    master.groupby(["year", "state_name"], as_index=False)
          .agg(total_crime=("crime_count", "sum"))
)

# 2) District-wise yearly totals (hotspot detection)
district_year = (
    master.groupby(["year", "state_name", "district_name"], as_index=False)
          .agg(total_crime=("crime_count", "sum"))
)

# 3) Crime-type distribution per year (category-based)
type_year = (
    master.groupby(["year", "category", "crime_type"], as_index=False)
          .agg(total_crime=("crime_count", "sum"))
)

print("✅ state_year:", state_year.shape)
print("✅ district_year:", district_year.shape)
print("✅ type_year:", type_year.shape)

state_year.head()

✅ state_year: (216, 3)
✅ district_year: (6506, 4)
✅ type_year: (3232, 4)

   year                   state_name  total_crime
0  2017  Andaman And Nicobar Islands      71364.0
1  2017               Andhra Pradesh     392867.0
2  2017            Arunachal Pradesh     156084.0
3  2017                        Assam     440398.0
4  2017                        Bihar     615218.0

In [3]:
import os
from pathlib import Path

PROJECT_ROOT = Path.cwd()

# If you're inside notebooks folder, go one level up
if (PROJECT_ROOT / "data").exists() is False:
    PROJECT_ROOT = PROJECT_ROOT.parent

print("PROJECT_ROOT:", PROJECT_ROOT)

shp_path = PROJECT_ROOT / "data" / "geo" / "Admin2.shp"
print("SHP PATH:", shp_path)
print("Exists?", shp_path.exists())

PROJECT_ROOT: d:\crimewatch
SHP PATH: d:\crimewatch\data\geo\Admin2.shp
Exists? True

In [4]:
import geopandas as gpd

gdf = gpd.read_file(shp_path)
gdf.head()

               ST_NM                                           geometry
0  Arunachal Pradesh  POLYGON ((96.08866 29.45997, 96.09428 29.45477...
1              Assam  POLYGON ((95.97166 27.96254, 95.97174 27.96227...
2         Chandigarh  POLYGON ((76.77175 30.79498, 76.77231 30.7942,...
3          Karnataka  POLYGON ((77.32647 18.45884, 77.32648 18.45803...
4            Manipur  POLYGON ((94.57315 25.69156, 94.57522 25.69094...

In [5]:
import geopandas as gpd
gdf = gpd.read_file("../data/geo/Admin2.shp")
gdf.head()

               ST_NM                                           geometry
0  Arunachal Pradesh  POLYGON ((96.08866 29.45997, 96.09428 29.45477...
1              Assam  POLYGON ((95.97166 27.96254, 95.97174 27.96227...
2         Chandigarh  POLYGON ((76.77175 30.79498, 76.77231 30.7942,...
3          Karnataka  POLYGON ((77.32647 18.45884, 77.32648 18.45803...
4            Manipur  POLYGON ((94.57315 25.69156, 94.57522 25.69094...

In [6]:
print(gdf.columns)

Index(['ST_NM', 'geometry'], dtype='object')

In [2]:
from pathlib import Path
import pandas as pd

# Find project root automatically (folder containing "data")
ROOT = Path.cwd()
while ROOT != ROOT.parent and not (ROOT / "data").exists():
    ROOT = ROOT.parent

DATA_PATH = ROOT / "data" / "processed" / "master_crime_long.csv"
print("✅ Project Root:", ROOT)
print("✅ CSV Path:", DATA_PATH)
print("✅ Exists:", DATA_PATH.exists())

df = pd.read_csv(DATA_PATH)
print("✅ Loaded:", df.shape)
print(df.columns)
print(df["year"].min(), df["year"].max())
print(df["state_name"].nunique(), df["district_name"].nunique())
print(df["category"].value_counts().head(20))

✅ Project Root: d:\crimewatch
✅ CSV Path: d:\crimewatch\data\processed\master_crime_long.csv
✅ Exists: True
✅ Loaded: (2870817, 10)
Index(['year', 'state_name', 'state_code', 'district_name', 'district_code',
       'registration_circles', 'crime_type', 'crime_count', 'category',
       'source_file'],
      dtype='object')
2017 2022
36 1106
category
ipc_total                 627996
ipc_by_juveniles          627996
sll_crimes                388433
crime_against_children    276692
crime_against_women       228811
cyber_crime               223524
crime_against_st          213252
crime_against_sc          207597
missing_persons            76516
Name: count, dtype: int64

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\crimewatch\data\processed\master_crime_long.csv")
print(df.shape)
print(df.columns)

(2870817, 10)
Index(['year', 'state_name', 'state_code', 'district_name', 'district_code',
       'registration_circles', 'crime_type', 'crime_count', 'category',
       'source_file'],
      dtype='object')

In [4]:
import os
os.chdir(r"D:\crimewatch")
print("✅ CWD set to:", os.getcwd())

✅ CWD set to: D:\crimewatch

In [5]:
import pandas as pd
df = pd.read_csv("data/processed/master_crime_long.csv")
print(df.shape)

(2870817, 10)